name: Build and Push Docker Image

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ github.repository }}:${{ github.sha }}  # Tag with commit SHA
        file: ./Dockerfile

    - name: Scan with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=mona-13
          -Dsonar.projectKey=mona-13
          -Dsonar.python.coverage.reportPaths=coverage.xml# name: "sonar_cloud_scan_github_actions"
# on:
#   push:
#     branches:
#       - main  
      

# jobs:
#   DemoSonarCloudSCan:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#             fetch-depth: 0
#       - name: SonarCloud Scan
#         uses: sonarsource/sonarcloud-github-action@master
#         env:
#             GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         with:
#           args: >
#               -Dsonar.organization=mona-13
#               -Dsonar.projectKey=mona-13
#               -Dsonar.python.coverage.reportPaths=coverage.xml
